### ISSUE TITLE
Is the `Traversal` pattern possible with `ModelRW*`?

### ISSUE THREAD

**Issue by fosskers** [ochrons/diode#18]
A toy example. Given the following model structure:
```scala
 case class MsgDB(users: Seq[User])
 case class User(id: String, msgs: Seq[String])
```
and an action:
```scala
case class Post(user: String, msg:String)
```
I'd like to handle a `Post` action, but only if that user exists. Thinking in a lensy way, I'd like a:

```haskell
-- | Traverses into a User's message list, if that user exists.
msgsT :: String -> Traversal' MsgDB [String]
```
is this possible with Diode's `Model*` pseudo-Lenses?

Ideally I'd have:
```scala
val msgsT: ModelRW[MsgDB, Seq[String]] = ...

val postH = new ActionHandler(msgsT) {
  override def handle = {
    case Post(u,m) => updated(value :+ m)  
  }
}
```

**Comment by fosskers** [comment]
I notice that the `u` in `Post` becomes redundant.

**Comment by ochrons** [comment]
If you do not handle the `Post` action, it will be an error. What you need to do is to check in your handler is the user exists and then return either `updated(...)` or `noChange` accordingly.

**Comment by fosskers** [comment]
Right, manually. So the answer to my original question is "no", then?

**Comment by ochrons** [comment]
As the action handler is just a partial function, you are free to implement it in any way you find appropriate. You can build support machinery to enable functionality such as you described.

`ActionHandler` is such a support class to make is easier to work with `ModelRW` in typical use cases.

**Comment by fosskers** [comment]
Thank you, this is likely to come in handy.
