### ISSUE TITLE
foldHandlers not working in 0.5.2

### ISSUE THREAD

**Issue by erinmez** [ochrons/diode#20]
First of all, congratulations to such a thoughtful library!
I have experienced in my usage just a small glitch so far. The same action is only handled by one of the handlers. Before slimming down my example, I noticed that CircuitTests (see link below) is comparing (wrongly) against the initial value 42, whereas it should compare to 43. I guess that's the reason why the test case doesn't fail and the bug is not showing up.
https://github.com/ochrons/diode/blob/master/diode-core/shared/src/test/scala/diode/CircuitTests.scala#L363

**Comment by ochrons** [comment]
LOL, great testing! Fixing that for 0.6.0
