### ISSUE TITLE
React elements not receiving re-render calls on pertinent circuit state changes

### ISSUE THREAD

**Issue by gtkovas** [ochrons/diode#30]
I'm having trouble with diode's React interoperability, specifically in changes to a Circuit's state not triggering re-rendering of React elements. However, I fairly new to both Diode and React so the fault may be mine.

I have a widget that holds a list of values:

```
val DiodeClassificationBox = ReactComponentB[ModelProxy[Pot[PaperInfoShort]]]("ClassBox")
    .render_P { case proxy =>
      <.div(
        TitleBar("Classification"),
        ReadOnlyInputBar(proxy.value.get.mrPrim),
        <.div(
          ^.onMouseUp --> proxy.dispatch(HighlightChange),
          ReadOnlyInputBar((for(s <- proxy.value.get.secondaries) yield s.classCode).mkString(" "))
        )
      )
  }.build
  val ClassificationBox = SelectCircuit.connect(_.paperInfo)(p => DiodeClassificationBox(p))

```

And another widget that holds a selected value and is only rendered when that selected value matches one of the values in the above list. This selected value is set with the Callback "HighlightChange" above.

```
val DiodeChangeClassButton = ReactComponentB[ModelProxy[String]]("SaveButton")
    .render_P { case proxy =>
      if(proxy.value != "")
        <.div(
          ^.cursor := "pointer",
          ^.onClick --> proxy.dispatch(ChangeClass(proxy.value)),
          "String is: " + proxy.value
        )
      else
        <.div()
  }.build
  val ChangeClassButton = SelectCircuit.connect(_.selection)(p => DiodeChangeClassButton(p))
```

Both of these are rendered inside a holder widget.

However, when HighlightChange is fired by making a selection and the selection string is changed in the Circuit state, the ChangeClassButton is not getting a render call (meaning the button does not appear as intended). 

Am I incorrect in thinking that all element connected into SelectCircuit's "_.selection" should be getting a rerender call when _.selection changes?

**Comment by ochrons** [comment]
Did you get this resolved?

**Comment by gtkovas** [comment]
Ah, yes! Apologies for forgetting to close. I feel rather sheepish to admit I was using a pre 1.0 release. Upgrading resolved the problem.

**Comment by ochrons** [comment]
Good to hear 👍
