### ISSUE TITLE
The live demonstration does not allow an item to be edited

### ISSUE THREAD

**Issue by oswaldo** [ochrons/diode#31]
Hello,

The live demonstration available at http://ochrons.github.io/diode/examples/todomvc/#/ has a bug. Double clicking an item for editing it, as mentioned in the page itself, displays the editing field but as soon as any character is typed, the content gets reset to the original.

Tested in firefox and chrome.

Regards,
Oswaldo

**Comment by ochrons** [comment]
Seems to work now.
