### ISSUE TITLE
examples dont build right now

### ISSUE THREAD

**Issue by joss75321** [ochrons/diode#33]
Nice library, looks very promising. I came across a couple of minor issues:

examples/treeview> sbt "~fastOptJS"        results in

[error] (*:update) sbt.ResolveException: unresolved dependency: me.chrons#diode-core_sjs0.6_2.11;1.0.1-SNAPSHOT: not found

I changed build.sbt to reference  "me.chrons" %%% "diode-core" % "1.0.0"  instead of "me.chrons" %%% "diode-core" % "1.0.1-SNAPSHOT" and life was ok.

Also, I think http://ochrons.github.io/diode/examples/raf/ is not quite right at the moment... the pulldown is empty so it doesnt seem to do anything

**Comment by ochrons** [comment]
Yeah, the examples are using a newer snapshot version of Diode, as they are used to test changes in the Diode library itself. You can pull a (release) tagged version of the source from GitHub to get examples that use a particular version of the library.

As for the RAF example online, the dropdown works fine on my Chrome. What browser/OS are you using?

**Comment by joss75321** [comment]
The RAF problem turned out to be a stupid local network issue blocking
jquery.com, sorry about that, it works fine now.

**Comment by ochrons** [comment]
Another solution to the first problem is to locally build a SNAPSHOT version of Diode and then `publishLocal` it.
