### ISSUE TITLE
Pot.pending(): argument startTime is ignored in implementations

### ISSUE THREAD

**Issue by helllamer** [ochrons/diode#37]
Hello.

According to [Pot.scala](https://github.com/ochrons/diode/blob/master/diode-data/shared/src/main/scala/diode/data/Pot.scala#L44), Pot have an abstract method `Pot.pending(startTime: Long = ...)`.
But, in implementations, argument `startTime` is ignored. For example, `Unavailable` contains this:
```
   override def pending(startTime: Long = new Date().getTime) = Pending()
```

`Ready[T]` contains similar code:
```
  override def pending(startTime: Long = new Date().getTime) = PendingStale(x)
```
Same for `Pending`, `PendingStale` and others.

This is designed for some reason or it should be fixed?
Thanks.

**Comment by ochrons** [comment]
This was probably just overlooked in the implementations, as the `startTime` parameter for pending is so rarely used. So it's definitely a bug.
